# Generated by Django 4.0.3 on 2022-09-23 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productcolor'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productimage'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productsize'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productattribute'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem', verbose_name='cartitem')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
    ]
