# Generated by Django 4.0.3 on 2022-09-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_product_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='product_attrs', to='shop.productsize'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
