# Generated by Django 4.0.3 on 2022-09-24 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_order_cart_item_cart_final_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='No Address given...', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
