# Generated by Django 4.0.3 on 2022-09-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_city_order_state_order_zip_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartitem',
            new_name='cart_item',
        ),
    ]
