# Generated by Django 4.1 on 2022-09-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_total',
        ),
    ]
