# Generated by Django 4.1 on 2022-09-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_cart_cart_item_remove_cart_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_item', to='shop.cartitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='final_total',
            field=models.FloatField(default=0),
        ),
    ]
