# Generated by Django 4.1 on 2022-09-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart_cart_item_cart_final_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_total',
        ),
    ]
