# Generated by Django 4.1 on 2023-01-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartitem_my_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size',
        ),
    ]
