# Generated by Django 4.1 on 2023-01-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_colors_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
