# Generated by Django 4.1 on 2023-04-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.cart'),
        ),
    ]
