# Generated by Django 4.1 on 2023-04-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_available_amount_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_amount',
        ),
    ]
