# Generated by Django 4.1 on 2023-04-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product_available_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='available_amount',
            field=models.IntegerField(default=1),
        ),
    ]
