# Generated by Django 4.1 on 2023-04-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productsize_available_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
