# Generated by Django 4.1 on 2023-05-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_delete_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
